### ISSUE TITLE
Unnecessary getQuestion function abstraction

### ISSUE THREAD

**Issue by shiryz** [WebAhead5/PlayGameOfThrones#10]
https://github.com/WebAhead5/PlayGameOfThrones/blob/0680f5a94d1763d38d4c772b651957d5838a0821/src/scripts/bl.js#L85-L87

You don't need a separate function for this

**Comment by fridabu** [comment]
We having a thoughts for future more complicated code in this function, for example to check if we reached the last question, changed to :
function getQuestion(index){
    if(index < questions.length){
        return questions[index];
    }
}
