### ISSUE TITLE
Skip button and the right answer

### ISSUE THREAD

**Issue by MoradAbed** [WebAhead5/PlayGameOfThrones#16]
1. https://github.com/WebAhead5/PlayGameOfThrones/blob/master/src/scripts/bl.js#L90-L92
// response for skip click
function skip(){
    if(lives > 0.5){
        lives-= 0.5;
    }
    changeUiToNextQuestion(getQuestion(++index), lives);

}

2. https://github.com/WebAhead5/PlayGameOfThrones/blob/master/src/scripts/bl.js#L113-L122
if(!answerClicked){
        answerClicked = true;
        if(chossenAnswer === rightAnswer){
             figure.style.border = '2px solid green';
        }else{
            figure.style.border = '2px solid red';
            lives -= 1;
        }
    }
}

So if you skip the question and your score is still bigger than 0.5 you have 2 rules applying on the act Lives -= 0.5 and -= 1 which subtracts 1.5 when your score is >0.5.
Besides, the right question will be bordered with a green border even before submitting the answer (is that kind of hint from you;-)? ). I think it should be styled in the CSS with ": after".

**Comment by fridabu** [comment]
-These are two different functions that act as response for two different buttons - skip button and next question.
- About the green border - this is not a bug - this is the normal behavior- clicking  the answer will give the user response immediately - and next moves to next question.

- After clicking answer you can not change it.
